### ISSUE TITLE
Distinguish between removed and disabled Services in LDAP

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#106]
See https://github.com/SURFscz/SBS/issues/765

When SBS actually outputs the status of the ldap connection for a service, the behaviour should be like this:
 - if a Service is disabled, keep the main structure (`dc=service`,  `cn=admin`, `dc=ordered/flat`, `ou=Groups/People`) but remove the groups and users.  Also set the admin password to disabled (should be automatic as SBS shoudl return `None` for the passwd)
 - is a Service is removed (i.e., not present in the output of `plsc/sync`), remove the entire service subtree.

**Comment by HarryKodden** [comment]
Correction: Above test result are run agaunst main branch, which is not the branch containing the action result.
Testing against the correct branch ('fix-ldap-enabled') gives different results.
* When Service is switch to 'disabled' in SRAM, indeed contents is not pushed to the LDAP.
* However, the tests break on this fix. The test should also take the 'ldap_enabled: Yes/No' into account.

Current observation when Service is ldap disabled in SRAM:

INFO     tests.test_all:test_all.py:24 *** Checking LDAP: o=uuc.ai_computing,dc=ordered,dc=https://cloud,dc=sram,dc=tld
ERROR    tests.test_all:test_all.py:32 No results for: o=uuc.ai_computing,dc=ordered,dc=https://cloud,dc=sram,dc=tld
INFO     tests.base_test:base_test.py:124 BaseTest tearDown
=========================================================================================== short test summary info ============================================================================================
FAILED tests/test_all.py::TestAll::test_ldap_services - AssertionError: False is not true

**Comment by HarryKodden** [comment]
Commit:
https://github.com/SURFscz/plsc/commit/7b797d89cb80610af75d1ce321fa4fbec763656e

**Comment by baszoetekouw** [comment]
Ah, this branch has indeed not bene merged yet.  Let's put this in v27.
