### ISSUE TITLE
Containerize plsc

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#110]
See SURFscz/SRAM-deply#469

Create a container that runs plsc.

Make this smart, so we don't need to install cron/systemd/etc in the container.

**Comment by HarryKodden** [comment]
See PR https://github.com/SURFscz/plsc/pull/112

**Comment by baszoetekouw** [comment]
@HarryKodden kun jij deze Docker baseren op de `python311` container uit https://github.com/SURFscz/OpenConext-BaseContainers ?
