### ISSUE TITLE
Services without connected COs should be created in ldap

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#114]
The tree should be rather empty, of course, but it is confusing for service owner otherwise.

**Comment by mrvanes** [comment]
What is empty? Like https://github.com/SURFscz/plsc/issues/121 it seems ambiguous what the definition of empty is.

**Comment by mrvanes** [comment]
Fixed in https://github.com/SURFscz/plsc/pull/122/commits/af891fe013be9f021ed70456db6415039fae926f
With these contents:
![image](https://github.com/SURFscz/plsc/assets/1901782/bbeb0d69-532c-44af-9aab-e659789df1cb)

**Comment by baszoetekouw** [comment]
Werk bijna, maar nog niet helemaal:  helemaal verse service krijgen alleen `cn=admin` en `dc=ordered`.  Please also add `dc=flat`, and `ou=Groups` and `ou=Users` in flat.
