### ISSUE TITLE
Move to different identifier for Services in PLSC

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#117]
Currently, services are identified by their entity_id in the ldap tree.  The DNs look like `dc=http://test.beta.sram.surf.nl/test1,dc=services,dc=sram,dc=surf,dc=nl` for example.

This is annoying for two reasons:
 - sometimes the entity_id changes; this should not affect the ldap
 - entity_ids can be too complex to use in DNs (leads to escaping troubles)

Therefore, SBS will introduce a new `ldap_identifier` attribute for services (see https://github.com/SURFscz/SBS/issues/1054).  plsc should use this instead of the entity_id to build Service trees.

**Comment by mrvanes** [comment]
Fixed in https://github.com/SURFscz/plsc/pull/122/commits/8d26d7174ffd47fff7a429a1d8d289b7230be4f2
![image](https://github.com/SURFscz/plsc/assets/1901782/05c6579d-3fc9-4d6b-bb9c-f21d88a3c751)

**Comment by baszoetekouw** [comment]
Works;  only now it's very hard to distinguish different orgs.  Please add `objectclass=extensibleObject` and a name (`short_name`) and `displayName` (`name`) to all top-level service objects.

**Comment by mrvanes** [comment]
Fixed in https://github.com/SURFscz/plsc/pull/123/commits/faadd9f97ded15e11eda10aa9c4483d2aeb8603a but /api/plsc/sync does not contain service[short_name] so assigned entity_id for now.

**Comment by baszoetekouw** [comment]
Service abbreviation is also exposed in SBS, so name in ldap is now filled with abbreviation:
![Screenshot 2023-12-06 at 12 44 27](https://github.com/SURFscz/plsc/assets/1461740/345ba222-025c-4a78-a3a9-5bf424b3bff5)
