### ISSUE TITLE
As service admin I want to view the last login date for a user in LDAP

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#30]
Belangrijkste vraag: in welk attribuut willen we dit stoppen?

**Comment by baszoetekouw** [comment]
Next step: maak een ontwerp voor dat custom ldap schema dat we willen gaan gebruiken

**Comment by baszoetekouw** [comment]
Zie #55

**Comment by mrvanes** [comment]
Wat worden de brongegevens van SBS om deze te vullen?

**Comment by baszoetekouw** [comment]
SBS heeft (sinds kort denk ik) `users.[n].last_login_date` in de `plsc/sync`

**Comment by baszoetekouw** [comment]
Oh, en we moeten dit een klein beetje privacy-vriendelijk maken denk ik en niet de precieze datetime van de laatste login opnemen, maar een wat grovere afronding.  Ik denk dat afronden op een week wel ok is; wat denkt @arnoutt ?

**Comment by baszoetekouw** [comment]
Ik zit nu wel te denken of het dan niet handiger is om in de ldap een "sramDaysInactive" op te nemen ipv `sramLastActivityDate`.  Dat rond ook makkelijker af.

**Comment by baszoetekouw** [comment]
Tested, works also on prod data (plsc run take a long time though)
