### ISSUE TITLE
plsc_flat zet voPersonStatus niet goed

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#40]
In het geval dat een gebruiker lid is van 2 COs waarvan er 1 expired is, gaat plsc_flat kapot.  Hij zet dan steeds in 1 run eerst de user op expires (voor de 1e CO) en an direct daarna op active.  Daardoor blijft hij bij elke plsc call die gebruikrs updaten.

Zie bijvoorbeeld (op prod):

```
bas@ldap-pf1:~$ journalctl -u plsc -n 1000|grep 8225| grep -A1 mvanes
jun 23 12:50:31 ldap-pf1 run.sh[8225]: INFO:root:[LDAP] Update: uid=mvanes,ou=People,dc=flat,dc=https://surfdev.grafana.net/saml/metadata,dc=services,dc=sram,dc=surf,dc=nl
jun 23 12:50:31 ldap-pf1 run.sh[8225]: INFO:root:[LDAP] Update will modify: [(1, 'voPersonStatus', None), (0, 'voPersonStatus', [b'expired'])]
--
jun 23 12:50:31 ldap-pf1 run.sh[8225]: INFO:root:[LDAP] Update: uid=mvanes,ou=People,dc=flat,dc=https://surfdev.grafana.net/saml/metadata,dc=services,dc=sram,dc=surf,dc=nl
jun 23 12:50:31 ldap-pf1 run.sh[8225]: INFO:root:[LDAP] Update will modify: [(1, 'voPersonStatus', None), (0, 'voPersonStatus', [b'active'])]
```

Het gewenste gedrag is:
 - gebruiker is `active` als hij in tenminste één (voor de dienst zichtbare en non-expired) CO ook `active` is

Los daarvan worden groepslidmaatschappen van expired lidmaatschappen niet getoond in `flat` (maar dat werkt nu al goed).

**Comment by mrvanes** [comment]
Fixed in https://github.com/SURFscz/plsc/pull/42

**Comment by baszoetekouw** [comment]
Staat op test
