### ISSUE TITLE
Logging werkt niet zoals verwacht.

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#41]
Ik had verwacht dat als ik `LOGLEVEL=DEBUG` zet in de environment, ik alle debugmessgaes uit plsc krijg.  Dat blijkt echter niet het geval: je krijgt alleen debug messages uit `plsc_ordered.py` en `plsc_flat.py`, en niet uit (bv) `sldap.py`.

Graag aanpassen (ik zou het zelf doen, maar ik snap niks van die python logging spullenboel...).

**Comment by HarryKodden** [comment]
Er zijn op dit moment 2 'main' modules (plsc_ordered en plsc_flat) en die roepen methods aan in sldap.py en sbs.py.
In de main modules wordt de logging geinitialiseerd:

```
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))
```
(dus logging details afhankelijk van je environment setting **LOGLEVEL** met default value **INFO**)

In de modules kan je naar deze actiev logging verwijzen door te initiaseren met:

```
logger = logging.getLogger()
```

Deze aanpassing is nu doorgevoerd, zodat alle logging nu netjes doorkomt.
