### ISSUE TITLE
Add policy url in service entry 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#43]
@venekamp heefy dit nodig voor het syncscript

**Comment by mrvanes** [comment]
labeledURI (labeledURIObject) lijkt eigenlijk de beste en enige kandidaat?
`labeledURI: http://test.com/ Foobar AUP`

https://backstage.forgerock.com/docs/ds/7/schemaref/at-labeledURI.html

**Comment by baszoetekouw** [comment]
@venekamp ik zal dit zo naar test deployen; kun jij testen of het dan voor jou voldoet?

**Comment by FlorisFokkinga** [comment]
Available in SBS:

![Image](https://user-images.githubusercontent.com/80269262/187427616-54961732-cf9e-46e8-8d08-2ec1127fa019.png)

**Comment by baszoetekouw** [comment]
Confirmed op VM:
