### ISSUE TITLE
optimalizaties waarschijnlijk nodig

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#45]
Okke heeft op test een bunchload testgebruikers toegevoegd om te testen nhoe SBS daarmee omgaat.  SBS redt het wel, maar plsc/slapd heeft het moeilijk.  Plsc runs op test duren nu grofweg 10 minuten en de slapd staat de helft van die tidj op de volle 100% te draaien. 

Kunnen we misschien plsc niet optimaliseren?

**Comment by mrvanes** [comment]
https://github.com/SURFscz/plsc/pull/47

**Comment by baszoetekouw** [comment]
voor v16

**Comment by baszoetekouw** [comment]
Current status on prod: run takes ~75 seconds.  we need to monitor this (see https://github.com/SURFscz/SRAM-deploy/issues/413)

The approach taken in this PR is probably ok, but plsc is getting more and more spaghettiesk, so I am hesitant to merge it at this point.
