### ISSUE TITLE
Support for multivalued 'voPersonExternalAffiliation'

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#56]
Multivalued `voPersonExternalAffiliation` are currently put in a single value, as a comma-separated value, for example:

```ldif
# bzoetekouw5, People, surf_demo.test, ordered.testdienst.services.sram-acc.surf.nl
dn: uid=bzoetekouw5,ou=People,o=surf_demo.test,dc=ordered,dc=testdienst,dc=services,dc=sram-acc,dc=surf,dc=nl
voPersonExternalAffiliation: member@test-idp.lab.surf.nl, employee@test-idp.lab.surf.nl
```

I assume this is an artifact from SBS (which combines the multiple values into a comma-separated string).  Please undo the concatenation in plsc and write them in the ldap as separate attribute values.

**Comment by baszoetekouw** [comment]
Vreemd genoeg gaat dit in de SAML- en OIDC-flows wel goed.

**Comment by mrvanes** [comment]
scoped_affiliations komen komma gescheiden uit SBS:
```, 'scoped_affiliation': 'member, student', ```

**Comment by mrvanes** [comment]
https://github.com/SURFscz/plsc/commit/2553baf7c630bff5d849cd790848cae8de54a893

**Comment by baszoetekouw** [comment]
confirmed on acc
