### ISSUE TITLE
Add admin email address to COs in ldap

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#74]
See SURFscz/SBS#194

**Comment by mrvanes** [comment]
Voorstel/Vraag
In de ordered tak:
```
dn: o=coname, dc=ordered,dc=service,...
mail: test@test.com
```
(dit mag van het schema!)

In de flat tak:
```
dn: cn=coname.@all,ou=Groups,dc=flat,dc=service,...
mail: test@test.com
```
(dit mag ook van het schema!)

En eventueel dan ook in?
```
dn: cn=coname.cogroup,ou=Groups,dc=flat,dc=service,...
mail: test@test.com
```
(dit mag ook)

**Comment by mrvanes** [comment]
Op dit moment lijkt de enige manier om een CO admin te vinden de volgende:
Loop over collaboration_memberships als co_member:
  Als co_member[role] = 'admin':
    admin_mails += co_member[user][email]

Wat doen we met meerdere admins? Multi-value mail?

**Comment by baszoetekouw** [comment]
Reminder: docs aapassen

**Comment by baszoetekouw** [comment]
Confirmed on acc.  Docs on https://wiki.surfnet.nl/display/SRAM/LDAP+directory+structure updated.
