### ISSUE TITLE
Status van CO (active/expired) in ldap

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#81]

**Comment by baszoetekouw** [comment]
Zie ook #55

**Comment by baszoetekouw** [comment]
Nu worden de users van een expired CO allemaal individueel als expired getoond (https://github.com/SURFscz/plsc/blob/main/sbs.py#L185-L188).  Dat is niet echt praktisch voor diensten.

**Comment by mrvanes** [comment]
En wat is dan precies de bedoeling?

**Comment by baszoetekouw** [comment]
We moeten een expired attribuut op de CO zetten denk ik (en/of de nbijbehorende groepen), niet op de persoon

**Comment by baszoetekouw** [comment]
Dit werkt nog niet op test.  Als een CO expired is, worden alleen alle gebruikers expired, en niet de CO (of de @all-group) zelf.

**Comment by baszoetekouw** [comment]
Het helpt als je de goede versie deployt....
Werkt dus gewoon.
