### ISSUE TITLE
Don't remove Service if there are no connected COs

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/plsc#94]
When the last CO connection is removed from a Service, plsc now removed the entire service (incl the admin password).  This is undesirable; the entry should exist/be created, buit without any members/groups.

**Comment by mrvanes** [comment]
Stel, dit is de content van de service met 1 CO
![Image](https://github.com/SURFscz/plsc/assets/1901782/3c2c068f-53d9-4e09-84cc-e3b99e267355)

Wat wil je nu dat er hier bij het verwijderen uit uva.uu_short gebeurt?
https://github.com/SURFscz/plsc/blob/main/plsc_ordered.py#L431

**Comment by HarryKodden** [comment]
Works OK 


![Image](https://github.com/SURFscz/plsc/assets/1842889/f86e5f3f-d168-436c-8b44-546d980515b5)
